clc; clear;

Q = 2^16;

% Read LUT generated by Verilog
lut = load('lut.txt');

% read Verilog output file
data = load('results.txt');

a_vals  = data(:,1);
b_vals  = data(:,2);
verilog_q16 = data(:,3);

% open output file
fid = fopen('matlab_verification.txt','w');
fprintf(fid,'a b verilog_result matlab_result exact_value error_mv error_exact\n');

for k = 1:length(a_vals)

    a = a_vals(k);
    b = b_vals(k);

    % Newton Q16
    q_a = a * Q;
    q_b = b * Q;

    d = q_b;
    shift = 0;

    % normalization
    while d >= (1*Q)
        d = floor(d/2);
        shift = shift + 1;
    end

    while d < (0.5*Q)
        d = d * 2;
        shift = shift - 1;
    end

    % initial guess
    index = floor((d - 32768) / 512);   % same as >>>9 in Verilog
    
    % Safety clamp
    if index < 0
        index = 0;
    elseif index > 63
        index = 63;
    end
    
    x = lut(index + 1);
    
    % Newton iterations
    for i = 1:3
        t1 = floor((d * x)/Q);
        t2 = 2*Q - t1;
        x  = floor((x * t2)/Q);
    end

    % undo normalization
    if shift >= 0
        x = floor(x / (2^shift));
    else
        x = x * (2^(-shift));
    end

    % final multiply
    matlab_q16 = floor((q_a * x)/Q);

    % convert to real
    verilog_real = verilog_q16(k)/Q;
    matlab_real  = matlab_q16/Q;
    exact        = a/b;
    error        = abs(matlab_real - verilog_real);
    error_exact  = abs(exact - verilog_real);

    % write to file
    fprintf(fid,'%d %d %.10f %.10f %.10f %.10e %.10e\n',a,b,verilog_real,matlab_real,exact,error,error_exact);

end

fclose(fid);